server:
  port: 8080
spring:
  application:
    name: "back-fondos"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
aws:
  region: "us-east-2"
  accessKeyId: ""
  secretAccessKey: ""
  dynamodb:
    endpoint: "http://dynamodb.us-east-2.amazonaws.com"
app:
  saldoInicialCliente: 500000
